"""create score table

Revision ID: e89ce2503782
Revises: f6453a26e516
Create Date: 2022-09-27 14:07:40.570919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import ForeignKey


# revision identifiers, used by Alembic.
revision = 'e89ce2503782'
down_revision = 'f6453a26e516'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    

    op.create_table(
        'scores',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('rate', sa.Float, nullable=False),
        sa.Column('user_id', sa.Integer,ForeignKey("users.id"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('scores')
    # ### end Alembic commands ###
